version: '3'
services:
  chatgpt-monitor:
    build:
      context: .
      args:
        - PIP_INDEX_URL=https://mirrors.aliyun.com/pypi/simple/
        - PIP_TRUSTED_HOST=mirrors.aliyun.com
    container_name: chatgpt-monitor
    environment:
      - SENDER_EMAIL=${SENDER_EMAIL}
      - RECEIVER_EMAIL=${RECEIVER_EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - SMTP_SERVER=${SMTP_SERVER:-smtp.qq.com}
      - SMTP_PORT=${SMTP_PORT:-465}
      - SMTP_SSL=${SMTP_SSL:-true}
      - USER_COOKIE=${USER_COOKIE}
      - THRESHOLD=${THRESHOLD:-1600}
      - CHECK_INTERVAL=${CHECK_INTERVAL:-600}
    restart: always 